# Generated by Django 5.0.1 on 2024-01-04 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, default="")),
                ("cooking_steps", models.TextField(blank=True, default="")),
                ("cooking_time", models.IntegerField()),
                ("img", models.ImageField(upload_to="")),
                ("add_time", models.DateField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        default="Author unknown",
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="recipeapp.author",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        default="Category unknown",
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="recipeapp.category",
                    ),
                ),
            ],
        ),
    ]
